
module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    UPDATE_USER_EMAIL: "UPDATE_USER_EMAIL",
    UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",

    ADD_NEW_EVENT: "ADD_NEW_EVENT",
    UPDATE_EVENT: "UPDATE_EVENT",

    ADD_NEW_TEAM: "ADD_NEW_TEAM",
    UPDATE_TEAM: "UPDATE_TEAM",

    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    EVENT_DELETE: "EVENT_DELETE",
    TEAM_DELETE: "TEAM_DELETE",
  },
});
