
module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    UPDATE_USER_EMAIL: "UPDATE_USER_EMAIL",
    UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",

    ADD_NEW_EVENT: "ADD_NEW_EVENT",
    UPDATE_EVENT: "UPDATE_EVENT",

    ADD_NEW_RESEARCH: "ADD_NEW_RESEARCH",
    UPDATE_RESEARCH: "UPDATE_RESEARCH",

    ADD_NEW_SLIDERNEWS: "ADD_NEW_SLIDERNEWS",
    UPDATE_SLIDERNEWS: "UPDATE_SLIDERNEWS",

    ADD_NEW_TEAM: "ADD_NEW_TEAM",
    UPDATE_TEAM: "UPDATE_TEAM",

    ADD_NEW_PROGRAM: "ADD_NEW_PROGRAM",
    UPDATE_PROGRAM: "UPDATE_PROGRAM",

    ADD_NEW_CAMPUS: "ADD_NEW_CAMPUS",
    UPDATE_CAMPUS: "UPDATE_CAMPUS",

    ADD_NEW_FACULTY: "ADD_NEW_FACULTY",
    UPDATE_FACULTY: "UPDATE_FACULTY",

    ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",

    ADD_NEW_COURSE: "ADD_NEW_COURSE",
    UPDATE_COURSE: "UPDATE_COURSE",

    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    EVENT_DELETE: "EVENT_DELETE",
    RESEARCH_DELETE: "RESEARCH_DELETE",
    SLIDERNEWS_DELETE: "SLIDERNEWS_DELETE",
    TEAM_DELETE: "TEAM_DELETE",
    PROGRAM_DELETE: "PROGRAM_DELETE",
    CAMPUS_DELETE: "CAMPUS_DELETE",
    FACULTY_DELETE: "FACULTY_DELETE",
    CATEGORY_DELETE: "CATEGORY_DELETE",
    COURSE_DELETE: "COURSE_DELETE"
  },
});
