
module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    ADD_NEW_ROOM: "ADD_NEW_ROOM",
    ADD_NEW_TESTIMONY: "ADD_NEW_TESTIMONY",
    ADD_NEW_GALLERY: "ADD_NEW_GALLERY",
    ADD_NEW_PARTNER: "ADD_NEW_PARTNER",
    ADD_NEW_EVENT: "ADD_NEW_EVENT",
    ADD_NEW_NEWS: "ADD_NEW_NEWS",
    ADD_NEW_TEAM: "ADD_NEW_TEAM",
    ADD_NEW_HOSTCENTER: "ADD_NEW_HOSTCENTER",
    ADD_NEW_PROGRAMS: "ADD_NEW_PROGRAMS",
    ADD_NEW_COURSE: "ADD_NEW_COURSE",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    PARTNER_DELETE: "PARTNER_DELETE",
    GALLERY_DELETE: "GALLERY_DELETE",
    ROOM_DELETE: "ROOM_DELETE",
    TESTIMONY_DELETE: "TESTIMONY_DELETE",
    EVENT_DELETE: "EVENT_DELETE",
    NEWS_DELETE: "NEWS_DELETE",
    TEAM_DELETE: "TEAM_DELETE",
    HOSTCENTER_DELETE: "HOSTCENTER_DELETE",
    PROGRAM_DELETE: "PROGRAM_DELETE",
    COURSE_DELETE: "COURSE_DELETE",
  },
});
